---
server:
    install: '1'
    timezone: UTC
    locale: en_US.UTF-8
    packages: ['curl', 'wget', 'nano', 'zlib-devel', 'bzip2-devel', 'openssl-devel', 'xz-libs', 'libselinux-python', 'MySQL-python']
vagrant_local:
    install: '1'
    vm: {
        base_box: salty-centos-6.5,
        hostname: dvo-generic,
        ip: 192.168.32.23,
        memory: '512',
        sharedfolder: ./,
        enableWindows: '0',
        useVagrantCloud: '1',
        syncType: nfs 
    }
php:
    install: '1'
    packages: ['php56w', 'php56w-common', 'php56w-cli', 'php56w-opcache', 'php56w-fpm', 'php56w-mysql', 'php56w-pdo', 'php56w-mcrypt', 'php56w-intl', 'php56w-devel']

mysql:
    install: '1'
    packages: ['mysql-community-server', 'mysql-community-client']
    root_password: Admin123
    hosts: ['127.0.0.1', 'dvo.dev', '::1', 'localhost']

nginx:
    install: '1'

web_server:
    app_web_dir: web
    server_user: www-data
    server_user_group: www-data
    server_name: dvo.dev
